#!/usr/bin/env python
import sys

if __name__ == "__main__":
	argv = sys.argv
	robotName = "ardrone"
	if len(argv) != 5:
		print("Input Spawner Requires 4 Arguments:\ninput_spawner.py [optimalCount] [randomCount] [maliciousCount] [processId]\n%s"%argv)
		sys.exit()

	#the variables
	optimalCount = int(argv[1])
	randomCount = int(argv[2])
	maliciousCount = int(argv[3])
	processId = int(argv[4])

	fakeInputNodes = "<!--Autogenerated spawning of fake crowd input-->\n"
	nodeTemplate = "\t<node name='%s%s' pkg='crowddrone_input_aggregator' type='%s' args='$(arg robot_namespace)'/>\n"

	executable = "optimal_input.py"
	for i in xrange(optimalCount):
		fakeInputNodes += nodeTemplate%("optimal",i,executable)

	executable = "random_input.py"
	for i in xrange(randomCount):
		fakeInputNodes += nodeTemplate%("random",i,executable)

	executable = "random_input2.py"
	for i in xrange(maliciousCount):
		fakeInputNodes += nodeTemplate%("malicious",i,executable)

	with open('/home/elliot/catkin_ws/src/crowddrone/crowddrone_gazebo/launch/testbedtemplate.launch', 'r') as template, open('/home/elliot/catkin_ws/src/crowddrone/crowddrone_gazebo/launch/testbed_%s.launch'%processId, 'w') as output:
		templateText = template.read()
		templateText = templateText.replace("<!-- SPAWN SIMULATED INPUT NODES HERE -->",fakeInputNodes)
		output.write(templateText)
